import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";

import NavWrapped from "./components/NavWrapped";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

const notoSerifBengali = Noto_Serif_Bengali({

  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Bazar Dor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
       <NavWrapped></NavWrapped> 
            
        <main>   {children} </main>
   
     <Footer></Footer>
      <Toaster></Toaster>
        </body>

    </html>
  );
}
