import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NavWrapped from "./components/NavWrapped";

const notoSerifBengali = Noto_Serif_Bengali({

  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Bazar Dor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <NavWrapped></NavWrapped>     
        <main>   {children} </main>
     <ToastContainer></ToastContainer>
        </body>
    </html>
  );
}
